### PR TITLE
add handling of multi-valued fields

### PR DESCRIPTION
**Pull request by Yvem**
cf. the readme

### CODE REVIEW

**Comment by chpill** [comment]
:ok:

**Comment by highfivedenis** [comment]
:ok:

**Comment by hugo-agbonon** [comment]
Why the .editorconfig ? Our other projects use jshint + jscs :disappointed:

**Comment by Yvem** [comment]
.editorconfig has nothing to do with jshint + jscs :-) http://editorconfig.org/

**Pull request merged**
